#!/bin/bash
# Script to deploy dotfiles and stuff

# install vim rtorrent zsh
# install steam lib32-nvidia-340xx-libgl wine
# install gnome

# scp -r lynzh@[REDACTED]:configs configs

# make mountpoints for extra disks

[ -d /mnt/ext1 ] && sudo mount /dev/sdc1 /mnt/ext1 || \
[ ! -d /mnt/ext1 ] && sudo mkdir /mnt/ext1 && mount /dev/sdc1 /mnt/ext1;

[ -d /mnt/ext2 ] && sudo mount /dev/sdd1 /mnt/ext2 || \
[ ! -d /mnt/ext2 ] && sudo mkdir /mnt/ext2 && mount /dev/sdd1 /mnt/ext2;

# Add external disks to group storage
sudo chgroup storage /mnt/ext1;
sudo chgroup storage /mnt/ext2;

# Let users read from external disks
chmod 755 /mnt/ext1; chmod 755 /mnt/ext2

# add user to group \storage\
sudo usermod -G storage lynzh

[ -b /dev/sdc1 ] && [ -d /mnt/ext1 ] && \
ln -s /mnt/ext1 $HOME/ext1;

[ -b /dev/sdd1 ] && [ -d /mnt/ext2 ] && \
ln -s /mnt/ext2 $HOME/ext2;

# Symlink up configs to ~/ 
ln -s $HOME/configs/.Xresources		$HOME/.Xresources
ln -s $HOME/configs/.rtorrent.rc 	$HOME/.rtorrent.rc
ln -s $HOME/configs/.vimrc 		$HOME/.vimrc 
ln -s $HOME/configs/.xinitrc		$HOME/.xinitrc
ln -s $HOME/configs/.profile		$HOME/.profile 
